//
// Created by t-yabeny on 4/6/2020.
//

#ifndef SHIP_STOWAGE_MODEL_ISTOWAGEPROCESS_H
#define SHIP_STOWAGE_MODEL_ISTOWAGEPROCESS_H

class IStowageProcess{

};

#endif //SHIP_STOWAGE_MODEL_ISTOWAGEPROCESS_H
