//
// Created by yahav on 06/04/2020.
//

#ifndef SHIP_STOWAGE_MODEL_IWEIGHTBALANCER_H
#define SHIP_STOWAGE_MODEL_IWEIGHTBALANCER_H

class IWeightBalancer {

};


#endif //SHIP_STOWAGE_MODEL_IWEIGHTBALANCER_H
